// Prints the Homebrew formula for a release: bun scripts/formula.ts <version> <checksums.txt>
const [version, checksumsFile] = process.argv.slice(2);
if (!version || !checksumsFile) {
  console.error("usage: bun scripts/formula.ts <version> <checksums.txt>");
  process.exit(2);
}

const REPO = "thanksduck/tunnel-manager";
const sums = new Map(
  (await Bun.file(checksumsFile).text())
    .trim()
    .split("\n")
    .map((l) => l.trim().split(/\s+/) as [string, string])
    .map(([sha, file]) => [file.replace(/^\*/, ""), sha]),
);

function asset(name: string, indent: string): string {
  const file = `tnl-${name}.tar.gz`;
  const sha = sums.get(file);
  if (!sha) throw new Error(`no checksum for ${file} in ${checksumsFile}`);
  return [`url "https://github.com/${REPO}/releases/download/v${version}/${file}"`, `sha256 "${sha}"`].map((l) => indent + l).join("\n");
}

console.log(`# Generated by the release workflow of ${REPO}. Do not edit by hand.
class Tnl < Formula
  desc "Tailscale-aware SSH tunnel manager with a live terminal dashboard"
  homepage "https://github.com/${REPO}"
  version "${version}"

  on_macos do
    depends_on arch: :arm64
${asset("darwin-arm64", "    ")}
  end

  on_linux do
    on_arm do
${asset("linux-arm64", "      ")}
    end
    on_intel do
${asset("linux-x64", "      ")}
    end
  end

  def install
    bin.install "tnl"
  end

  def caveats
    <<~EOS
      Run \`tnl\` to open the dashboard.

      To reconnect dropped tunnels automatically and start them at login:
        tnl daemon install
      Run it again after \`brew upgrade tnl\` to restart the supervisor on the new version.
    EOS
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/tnl --version").strip
  end
end`);
